package monte.carlo.view;

/**
 * Фрейм для отрисовки графиков распределений
 */
public class DistributionGraphic extends javax.swing.JFrame {

    /**
     * Creates new form DistributionGraphic
     */
    public DistributionGraphic() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("График распределения");
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setName("distributionGraphic"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 800));
        setSize(new java.awt.Dimension(400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
