package monte.carlo.view;

import monte.carlo.model.ModelInterface;
import monte.carlo.controller.ControllerInterface;
import monte.carlo.model.workinghoursencrease.RiskOfWorkingHoursEncrease;
import monte.carlo.ui.chart.WorkingHoursEncreaseRendererAdapter;
import monte.carlo.riskofworkinghoursencrease.ui.table.RiskOfWorkingHoursEncreaseTable;

/**
 * Класс представления.
 * Отрисовывает форму с компонентами ввода данных. Данные модели используются только для чтения.
 * Представление использует контроллер при обработке действий на форме. Контроллер инкапсулирует 
 * поведение, таким образом реализуется паттерн Стратегия.
 */
public class View extends javax.swing.JFrame implements ViewObserver {

    private ModelInterface model;
    private ControllerInterface controller;
    private DistributionGraphic distributionGraphic;
    
    /**
     * Конструктор представления.
     */
    public View(ControllerInterface controller, ModelInterface model) {
        this.controller = controller;
        this.model = model;
        this.distributionGraphic = new DistributionGraphic();
        model.registerObserver((ViewObserver)this);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        riskOfWorkingHoursEncreaseTable = new monte.carlo.riskofworkinghoursencrease.ui.table.RiskOfWorkingHoursEncreaseTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Программа поддержки принятия решений при внедрении ERP");
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 380));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 3));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Общие настройки", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Планируемое число испытаний");
        jPanel5.add(jLabel3);

        jSpinner1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(500, 0, 1000, 100));
        jSpinner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jSpinner1.setPreferredSize(new java.awt.Dimension(74, 23));
        jPanel5.add(jSpinner1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);
        jPanel5.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 3, 3));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 913));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Входные данные", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel6.setMinimumSize(new java.awt.Dimension(200, 35));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 65));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Планируемые трудозатраты");
        jLabel1.setToolTipText("");
        jPanel6.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("");

        jSpinner2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(350, 0, 1000000, 10));
        jSpinner2.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel6.add(jSpinner2);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Рассчитать");
        jButton1.setToolTipText("Рассчитать риск превышения трудозатрат");
        jButton1.setActionCommand("Рассчитать риск превышения трудозатрат");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jPanel1.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Выходные данные", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel7.setPreferredSize(new java.awt.Dimension(715, 300));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Вероятность превышения трудозатрат %");

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Сохранить в CSV");
        jButton2.setToolTipText("Сохранить в CSV");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.setEnabled(false);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("График распределения");
        jButton3.setToolTipText("График распределения");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        jScrollPane1.setAutoscrolls(true);

        riskOfWorkingHoursEncreaseTable.setToolTipText("");
        riskOfWorkingHoursEncreaseTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        riskOfWorkingHoursEncreaseTable.setAutoscrolls(false);
        riskOfWorkingHoursEncreaseTable.setFillsViewportHeight(true);
        riskOfWorkingHoursEncreaseTable.setShowGrid(false);
        riskOfWorkingHoursEncreaseTable.setShowHorizontalLines(true);
        riskOfWorkingHoursEncreaseTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(riskOfWorkingHoursEncreaseTable);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Трудозатраты", null, jPanel1, "");
        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Трудовые ресурсы", null, jPanel2, "");
        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Обьём работ", null, jPanel3, "");
        jPanel3.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Принятие решений", null, jPanel4, "");
        jPanel4.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.calcRiskOfWorkingHoursEncrease();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        WorkingHoursEncreaseRendererAdapter chartRenderer = 
                new WorkingHoursEncreaseRendererAdapter(model.getRiskOfWorkingHoursEncrease());
        distributionGraphic.getContentPane().removeAll();
        distributionGraphic.getContentPane().add(chartRenderer.createChartPanel());
        distributionGraphic.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    @Override
    public void updateRiskOfWorkingHoursEncrease() {
        RiskOfWorkingHoursEncrease riskOfWorkingHoursEncrease = model.getRiskOfWorkingHoursEncrease();
        jTextField2.setText(String.format("%.2f", riskOfWorkingHoursEncrease.getChanceOfWorkingHoursEncrease()));
        RiskOfWorkingHoursEncreaseTable table = (RiskOfWorkingHoursEncreaseTable)riskOfWorkingHoursEncreaseTable;
        table.reload(riskOfWorkingHoursEncrease.getRiskOfWorkingHoursEncreaseList());
    }

    @Override
    public void updateRiskOfLaborResources() {
        
    }
    
    @Override
    public void updateRiskOfExcessWork() {
        
    }

    /**
     * Кол-во испытаний
     * @return quantity of tests
     */
    public Integer getQuantityOfTests() {
        return (Integer)jSpinner1.getValue();
    }

    public Integer getPlannedWorkingHours() {
        return (Integer)jSpinner2.getValue();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable riskOfWorkingHoursEncreaseTable;
    // End of variables declaration//GEN-END:variables
}
